spring:
  security:
    user:
      name: admin
      password: admin

  boot:
    admin:
      client:
        url: http://localhost:7500

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security:
  oauth2:
    client:
      client-id: clientTest
      client-secret: clientSecret
      access-token-uri: http://localhost:9999/api/v1/oauth/token
      user-authorization-uri: http://localhost:9999/api/v1/oauth/authorize
      scope: read write
    resource:
      user-info-uri: http://localhost:9999/api/v1/users/me


springdoc:
  swagger-ui:
    disable-swagger-default-url: true